import React from 'react';

interface AboutPageProps {
  onStartPlay: () => void;
  onChooseMode: () => void;
}

const STATS = [
  { value: '30K+', label: 'Problems via MathNet' },
  { value: '47',   label: 'Countries & competitions' },
  { value: 'MOHS', label: 'Calibrated difficulty' },
  { value: 'AI',   label: 'Progressive hints' },
];

const FEATURES = [
  {
    icon: '∞',
    title: 'Endless Practice',
    body: 'The core loop. One problem at a time, drawn from a queue that weighs your topic strengths, recent solves, and timing — so you always work at the right edge of your skill.',
    primary: true,
  },
  {
    icon: '⏱',
    title: 'Competition Mode',
    body: 'A stricter timed format that mirrors a real contest session. Ideal for mock-competition days when you want to test yourself under pressure.',
    primary: false,
  },
  {
    icon: '💡',
    title: 'Progressive Hints',
    body: 'Three escalating hints per problem, generated by AI. Broad nudge → stronger guidance → near-complete solution. Reveal only what you need.',
    primary: false,
  },
];

const AboutPage: React.FC<AboutPageProps> = ({ onStartPlay, onChooseMode }) => {
  return (
    <>
      {/* Hero */}
      <section className="container mx-auto px-4 sm:px-8 pt-20 pb-16 text-center">
        <div className="inline-flex items-center gap-2 bg-secondary/80 border border-accent/20 rounded-full px-4 py-1.5 mb-8 text-sm text-light-secondary">
          <span className="w-1.5 h-1.5 rounded-full bg-accent inline-block shrink-0"></span>
          Built on MathNet &nbsp;·&nbsp; 30,000+ olympiad problems
        </div>

        <h1 className="text-5xl lg:text-6xl font-bold text-light leading-tight max-w-4xl mx-auto mb-6 tracking-tight">
          Olympiad training,{' '}
          <span className="bg-gradient-to-r from-accent via-yellow-300 to-accent bg-clip-text text-transparent">
            tuned to your level.
          </span>
        </h1>

        <p className="text-xl text-light/65 max-w-2xl mx-auto mb-10 leading-relaxed">
          Practice from a curated pool of competition problems with MOHS-scaled
          difficulty, adaptive recommendations, and progressive AI hints.
        </p>

        <div className="flex flex-col sm:flex-row items-center justify-center gap-4">
          <button
            onClick={onStartPlay}
            className="bg-accent text-primary font-bold text-lg px-10 py-3.5 rounded-xl hover:opacity-90 transition-all shadow-lg shadow-accent/25 hover:shadow-xl hover:shadow-accent/40 w-full sm:w-auto"
          >
            Start Endless Practice
          </button>
          <button
            onClick={onChooseMode}
            className="bg-secondary/60 border border-secondary text-light font-medium text-lg px-10 py-3.5 rounded-xl hover:border-accent/50 hover:text-accent transition-all w-full sm:w-auto"
          >
            Choose a Mode
          </button>
        </div>
      </section>

      {/* Stats strip */}
      <div className="border-y border-secondary/60 py-8 px-4">
        <div className="container mx-auto">
          <div className="grid grid-cols-2 md:grid-cols-4 gap-6 text-center">
            {STATS.map(stat => (
              <div key={stat.label}>
                <div className="text-3xl font-bold text-accent mb-1 font-mono">{stat.value}</div>
                <div className="text-sm text-light-secondary">{stat.label}</div>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* Feature cards */}
      <section className="container mx-auto px-4 sm:px-8 py-16">
        <div className="grid md:grid-cols-3 gap-5">
          {FEATURES.map(f => (
            <div
              key={f.title}
              className={`rounded-2xl p-8 border transition-colors ${
                f.primary
                  ? 'bg-accent/8 border-accent/30 hover:border-accent/60'
                  : 'bg-secondary/40 border-secondary hover:border-accent/30'
              }`}
            >
              <div className="text-3xl mb-4">{f.icon}</div>
              <h2 className={`text-xl font-bold mb-3 ${f.primary ? 'text-accent' : 'text-light'}`}>
                {f.title}
              </h2>
              <p className="text-light/65 leading-relaxed text-sm">{f.body}</p>
              {f.primary && (
                <button
                  onClick={onStartPlay}
                  className="mt-6 bg-accent text-primary font-semibold text-sm px-6 py-2 rounded-lg hover:opacity-90 transition-opacity"
                >
                  Start now →
                </button>
              )}
            </div>
          ))}
        </div>
      </section>

      {/* MathNet attribution */}
      <section className="container mx-auto px-4 sm:px-8 pb-16">
        <div className="bg-secondary/30 border border-secondary/60 rounded-2xl p-6 flex flex-col sm:flex-row items-start sm:items-center gap-5">
          <div className="flex-1">
            <p className="text-light font-semibold mb-1">Problems sourced from MathNet</p>
            <p className="text-sm text-light-secondary leading-relaxed">
              MathForces builds on MathNet — a large-scale multilingual olympiad dataset
              from MIT spanning 47 countries, 17 languages, and two decades of competition
              math — adding personalized recommendations and AI-generated hints on top.
            </p>
          </div>
          <a
            href="https://mathnet.mit.edu/"
            target="_blank"
            rel="noopener noreferrer"
            className="shrink-0 bg-secondary border border-accent/30 text-accent text-sm font-medium px-5 py-2 rounded-lg hover:bg-accent hover:text-primary transition-all"
          >
            mathnet.mit.edu ↗
          </a>
        </div>
      </section>
    </>
  );
};

export default AboutPage;
