import React from 'react';

const LAST_UPDATED = 'May 8, 2026';

const TermsPage: React.FC = () => {
  return (
    <div className="container mx-auto max-w-3xl px-6 py-16">
      <header className="mb-10">
        <h1 className="text-4xl lg:text-5xl font-bold bg-gradient-to-r from-accent to-light bg-clip-text text-transparent">
          Terms of Service
        </h1>
        <p className="mt-3 text-sm text-light-secondary">Last updated: {LAST_UPDATED}</p>
      </header>

      <section className="space-y-4 text-light/85 leading-relaxed">
        <p>
          MathForces is a personal, educational tool for practicing
          olympiad-level mathematics. It is provided as-is, solely as a study aid.
        </p>
      </section>

      <section className="mt-10">
        <h2 className="text-2xl font-bold text-accent mb-3">Where the problems come from</h2>
        <div className="space-y-4 text-light/85 leading-relaxed">
          <p>
            The problem set is sourced from{' '}
            <a
              href="https://mathnet.mit.edu/"
              target="_blank"
              rel="noopener noreferrer"
              className="text-accent underline underline-offset-2 hover:opacity-80 transition-opacity"
            >
              MathNet
            </a>
            , a curated collection of olympiad problems maintained at MIT.
            Problem statements, official solutions, source attributions
            (IMO, RMM, EGMO, BMO, AoPS, etc.), and difficulty estimates on
            the{' '}
            <a
              href="https://web.evanchen.cc/upload/MOHS-hardness.pdf"
              target="_blank"
              rel="noopener noreferrer"
              className="text-accent underline underline-offset-2 hover:opacity-80 transition-opacity"
            >
              MOHS scale
            </a>{' '}
            are taken from there. All credit for the problems and solutions
            belongs to their original authors and to the MathNet maintainers.
          </p>
          <p>
            If you are a problem author, contest organizer, or rights holder
            and would like content removed or attributed differently, please
            get in touch and it will be handled promptly: <a href="https://github.com/ervin-macic" className="text-accent underline underline-offset-2 hover:opacity-80 transition-opacity">contact</a>.
          </p>
        </div>
      </section>

      <section className="mt-10">
        <h2 className="text-2xl font-bold text-accent mb-3">Hints are AI-generated</h2>
        <div className="space-y-4 text-light/85 leading-relaxed">
          <p>
            The three progressive hints shown for each problem are
            generated by Google&apos;s Gemini model. They are intended to
            nudge you toward a solution when truly stuck, not to replace solving effort.
          </p>
          <p>
            Because they are model output, they may occasionally be
            misleading, incomplete, or factually wrong. Treat them as a
            study aid, double-check anything important against the official
            solution, and do not rely on them for graded or competitive
            work.
          </p>
        </div>
      </section>

      <section className="mt-10">
        <h2 className="text-2xl font-bold text-accent mb-3">No affiliation</h2>
        <div className="space-y-4 text-light/85 leading-relaxed">
          <p>
            MathForces is not affiliated with, endorsed by, or sponsored by
            the International Mathematical Olympiad (IMO), MathNet, the Art
            of Problem Solving (AoPS), or any other contest, organization,
            or institution referenced on the site. Names and trademarks
            belong to their respective owners and are used only to identify
            problem sources.
          </p>
        </div>
      </section>

      <section className="mt-10">
        <h2 className="text-2xl font-bold text-accent mb-3">Use at your own risk</h2>
        <div className="space-y-4 text-light/85 leading-relaxed">
          <p>
            Difficulty ratings, recommendations, and progress analysis are
            heuristic and approximate. They are useful for guiding practice
            but should not be read as objective measures of skill.
          </p>
        </div>
      </section>
    </div>
  );
};

export default TermsPage;
